# Generated by Django 3.1.7 on 2021-04-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Powers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'powers',
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_foundation', models.DateField()),
            ],
            options={
                'db_table': 'universe',
            },
        ),
        migrations.CreateModel(
            name='power_character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.powers')),
            ],
            options={
                'db_table': 'powers_characters',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.universe'),
        ),
    ]
